// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJNyUABIXyObk7arvflXmDoP5b-eyLYTY',
    appId: '1:23007514443:android:ff3431787ffc752a6522ce',
    messagingSenderId: '23007514443',
    projectId: 'my-test-fdf48',
    databaseURL: 'https://my-test-fdf48.firebaseio.com',
    storageBucket: 'my-test-fdf48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfaYxxFPMRXl6DmLUiSouuVwgehjZaYYU',
    appId: '1:23007514443:ios:8ef9ea1f39b51dbc6522ce',
    messagingSenderId: '23007514443',
    projectId: 'my-test-fdf48',
    databaseURL: 'https://my-test-fdf48.firebaseio.com',
    storageBucket: 'my-test-fdf48.appspot.com',
    androidClientId: '23007514443-2rin1fccdcs6vpeafbp9ohb0ptf42f8t.apps.googleusercontent.com',
    iosClientId: '23007514443-rhc9njo176l02nhfvhjel7grgd23adga.apps.googleusercontent.com',
    iosBundleId: 'com.unschooler.mentorai',
  );
}
